# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase hosting

on:
  push:
    branches: [ master ]
    paths:
      # hosting ディレクトリとgit直下のファイルが変更された時に実行する
      - 'functions/**'
      - '*'
      # Workflowが変更された時も実行する
      - '.github/workflows/firebase_hosting_deployment.yml'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v2
    
    - name: Extract environment variable
      run: echo "FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}" > .env

    - name: Start containers
      run: docker-compose up -d

    - name: Build React files
      run: docker-compose exec -T hosting yarn build

    - name: Publish
      run: docker-compose exec -T firebase_serve firebase deploy --only hosting
