# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase functions

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
    - '**'
    paths:
      # functions ディレクトリとgit直下のファイルが変更された時に実行する
      - 'functions/**'
      - '*'
      # Workflowが変更された時も実行する
      - '.github/workflows/firebase_functions_deployment.yml'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v2

    - name: Extract environment variable
      run: echo "FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}" > .env

    - name: build containers
      run: docker-compose build

    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: docker-compose run -T firebase_serve firebase deploy --only functions
