# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase hosting

on:
  push:
    branches:
    - '**'
    paths:
      # hosting ディレクトリとgit直下のファイルが変更された時に実行する
      - 'hosting/**'
      - '*'
      # Workflowが変更された時も実行する
      - '.github/workflows/firebase_hosting_deployment.yml'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v2
    
    - name: Extract environment variable
      run: echo "FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}" > .env

    - uses: satackey/action-docker-layer-caching@v0.0

    - name: build containers
      run: docker-compose build

    - name: Build React files
      run: docker-compose run -T hosting yarn build

    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: docker-compose run -T firebase_serve firebase deploy --only hosting
